server:
  port: 3006
#
#spring:
#  application:
#    name: user-service
#  config:
#    import: 'optional:configserver:'
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:3101/eureka/